Repository YAPP-Github/20th-iOS-Team-1-FE, pull requests merged in 2022-07, with the labels that each got.

#45 [Feature] Auth - 인증 파이프라인
  App/App.xcodeproj/project.pbxproj
  App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  App/App/Sources/Common/Coordinator/AppCoordinator.swift
  App/App/Sources/Common/Coordinator/AuthCoordinator.swift
  App/App/Sources/Common/Coordinator/Protocol/SceneCoordinator.swift
  App/App/Sources/Common/Coordinator/TabCoordinator.swift
  App/App/Sources/Common/Repository/AccountValidationRepository.swift
  App/App/Sources/Common/Repository/SignUpRepository.swift
  App/App/Sources/Common/UseCase/KeychainUseCase.swift
  App/App/Sources/Extension/String+Extension.swift
  App/App/Sources/Scenes/AuthScene/Entity/UserAccount.swift
  App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaReactor.swift
  App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaViewController.swift
  App/App/Sources/Scenes/ChattingScene/ChattingCoordinator.swift
  App/App/Sources/Scenes/GatherListScene/GatherListCoordinator.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileCoordinator.swift
  App/App/Sources/Scenes/SearchScene/SearchCoordinator.swift
Labels: 리뷰끝 머지됨 😘

#46 [Fix] 공통 - 코디네이터 네비게이션 오류 수정
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Common/Repository/SignUpRepository.swift
  App/App/Sources/Scenes/AuthScene/AuthCoordinator.swift
  App/App/Sources/Scenes/AuthScene/LoginScene/LoginReactor.swift
  App/App/Sources/Scenes/AuthScene/SignUpAgreementScene/SignUpAgreementReactor.swift
  App/App/Sources/Scenes/AuthScene/SignUpInfomationScene/SignUpInfomationReactor.swift
  App/App/Sources/Scenes/AuthScene/SignUpProfileScene/SignUpProfileReactor.swift
Labels: 리뷰끝 머지됨 😘

#47 [Feature] 서버로부터 받아온 Annotation을 통해 Pin 표시
  App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  App/App/Sources/Common/Coordinator/AppCoordinator.swift
  App/App/Sources/Common/Repository/GatherRepository.swift
  App/App/Sources/Extension/UIImage+Extension.swift
  App/App/Sources/Scenes/SearchScene/Entity/GatherCategory.swift
  App/App/Sources/Scenes/SearchScene/Entity/GatherConfigurationForAnnotation.swift
  App/App/Sources/Scenes/SearchScene/SearchViewController.swift
Labels: 리뷰끝 머지됨 😘

#54 [Feature] Search - BottomSheet UI 진행 중
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Common/Repository/GatherRepository.swift
  App/App/Sources/Scenes/SearchScene/Entity/GatherCategory.swift
  App/App/Sources/Scenes/SearchScene/Entity/GatherConfigurationForSheet.swift
  App/App/Sources/Scenes/SearchScene/MapViewBottomSheetContentView.swift
  App/App/Sources/Scenes/SearchScene/SearchReactor.swift
  App/App/Sources/Scenes/SearchScene/SearchViewController.swift
Labels: 리뷰끝 머지됨 😘

#58 [feat] AnnotationView 선택 시 BottomSheet 호출
  App/App.xcodeproj/project.pbxproj
  App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  App/App/Sources/Common/Repository/GatherRepository.swift
  App/App/Sources/Common/Service/Network/DTO/GatherConfigurationForSheetResponseDTO.swift
  App/App/Sources/Scenes/SearchScene/Entity/ClubStatus.swift
  App/App/Sources/Scenes/SearchScene/Entity/GatherConfigurationForSheet.swift
  App/App/Sources/Scenes/SearchScene/Entity/OwnerSex.swift
  App/App/Sources/Scenes/SearchScene/Entity/PetSizeType.swift
  App/App/Sources/Scenes/SearchScene/MapViewBottomSheetContentView.swift
  App/App/Sources/Scenes/SearchScene/SearchReactor.swift
  App/App/Sources/Scenes/SearchScene/SearchViewController.swift
Labels: 리뷰끝 머지됨 😘

#60 [Feature] DetailGather - 레이아웃 잡기
  App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  App/App/Sources/Common/Coordinator/AppCoordinator.swift
  App/App/Sources/Common/Repository/SignUpRepository.swift
  App/App/Sources/Common/Service/Network/Network/NetworkManager.swift
  App/App/Sources/Scenes/AuthScene/SignUpAgreementScene/SignUpAgreementViewController.swift
  App/App/Sources/Scenes/AuthScene/SignUpProfileScene/SignUpProfileViewController.swift
  App/App/Sources/Scenes/GatherListScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherListScene/DetailGatherScene/DetailGatherViewController.swift
Labels: 리뷰끝 머지됨 😘

#61 [feat] 모임 생성 화면 중 위치 설정 부분 UI 구성
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Extension/MKMapView+Extension.swift
  App/App/Sources/Extension/UIImage+Extension.swift
  App/App/Sources/Extension/UILabel+Extension.swift
  App/App/Sources/Scenes/SearchScene/SearchViewController.swift
Labels: 리뷰끝 머지됨 😘

#64 [Feature] DTO 추가 및 파일매니저 프록시 추가
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Common/Repository/DetailGatherRepository.swift
  App/App/Sources/Common/Repository/SignUpRepository.swift
  App/App/Sources/Common/Service/FileManager/FileExtension.swift
  App/App/Sources/Common/Service/FileManager/FileManageable.swift
  App/App/Sources/Common/Service/FileManager/FileManagerProxy.swift
  App/App/Sources/Common/Service/FileManager/FileManagerUseCase.swift
  App/App/Sources/Common/Service/FileManager/FileManagerUseCaseInterface.swift
  App/App/Sources/Common/Service/Network/DTO/Account/AccountValidationResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Account/AppleCredentialRequestDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Account/PetInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Account/SexDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Account/SignUpAccountDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Account/SocialTypeDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubCreateRequestDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubDetailInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubFIndDetailResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/CommentInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/LeaderInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/ClubInfosResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Common/AccountInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Common/EligibleSexDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Common/ExceptionDetailResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Common/ExceptionResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Common/ExceptionResponseInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Common/StatusDTO.swift
  App/App/Sources/Common/Service/Network/DTO/ContentResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/EligibleBreedDTO.swift
  App/App/Sources/Common/Service/Network/DTO/GatherConfigurationForSheetResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/GatherListResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Token/TokenResponseDTO.swift
  App/App/Sources/Common/Service/Network/Network/NetworkManageable.swift
  App/App/Sources/Common/Service/Network/Network/NetworkManager.swift
  App/App/Sources/Extension/FileManager+Extension.swift
  App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaViewController.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListViewController.swift
Labels: 리뷰끝 머지됨 😘

#69 [feat] 공통 - 런치스크린 추가 및 로그인 화면 싱크
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenDog.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenDog.imageset/Group 160@1x.png
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenDog.imageset/Group 160@2x.png
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenDog.imageset/Group 160@3x.png
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenLogo.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenLogo.imageset/Logo_L@1x.png
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenLogo.imageset/Logo_L@2x.png
  App/App/Resources/Assets.xcassets/Image/Logo/launchScreenLogo.imageset/Logo_L@3x.png
  App/App/Resources/Base.lproj/LaunchScreen.storyboard
  App/App/Sources/Application/AppDelegate.swift
  App/App/Sources/Scenes/AuthScene/LoginScene/LoginViewController.swift
Labels: 리뷰끝 머지됨 😘

#70 [Feature] 공통 - 자동로그인
  App/App/Sources/Application/AppDelegate.swift
  App/App/Sources/Application/SceneDelegate.swift
  App/App/Sources/Common/Coordinator/AppCoordinator.swift
  App/App/Sources/Common/Repository/ProfileRespository.swift
  App/App/Sources/Common/Service/Network/APIConstants.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileCoordinator.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileMainRepositoryInterface.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileReactor.swift
Labels: 리뷰끝 머지됨 😘, _요구사항

#76 [Feature] 모임 / 인증
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Application/AppDelegate.swift
  App/App/Sources/Application/SceneDelegate.swift
  App/App/Sources/Common/Coordinator/AppCoordinator.swift
  App/App/Sources/Common/Coordinator/TabCoordinator.swift
  App/App/Sources/Common/Repository/CommentRepository.swift
  App/App/Sources/Common/Repository/GatherListRepository.swift
  App/App/Sources/Common/Service/Keychain/KeychainProvider/KeychainAccount.swift
  App/App/Sources/Common/Service/Network/APIConstants.swift
  App/App/Sources/Common/Service/Network/DTO/ClubInfosResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/ContentResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/GatherListResponseDTO.swift
  App/App/Sources/Scenes/AuthScene/AuthCoordinator.swift
  App/App/Sources/Scenes/AuthScene/Entity/Authentification.swift
  App/App/Sources/Scenes/AuthScene/LoginScene/LoginReactor.swift
  App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaViewController.swift
  App/App/Sources/Scenes/AuthScene/SignUpPrivacyPolicyScene/SignUpPrivacyPolicyViewController.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentRepositoryInterface.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListCoordinator.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListReactor.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListRepositoryInterface.swift
Labels: 리뷰끝 머지됨 😘

#79 [Feature] 마이페이지 UI 수정 및 추가사항 적용
  App/App.xcodeproj/project.pbxproj
  App/App/Resources/Assets.xcassets/Image/Common/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/emptyIcon.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/emptyIcon.imageset/img_empty.png
  App/App/Resources/Assets.xcassets/Image/Common/emptyIcon.imageset/img_empty@2x.png
  App/App/Resources/Assets.xcassets/Image/Common/emptyIcon.imageset/img_empty@3x.png
  App/App/Resources/Assets.xcassets/Image/Common/largeSizePet.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/largeSizePet.imageset/my moim.png
  App/App/Resources/Assets.xcassets/Image/Common/largeSizePet.imageset/my moim@2x.png
  App/App/Resources/Assets.xcassets/Image/Common/largeSizePet.imageset/my moim@3x.png
  App/App/Resources/Assets.xcassets/Image/Common/middleSizePet.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/middleSizePet.imageset/my moim.png
  App/App/Resources/Assets.xcassets/Image/Common/middleSizePet.imageset/my moim@2x.png
  App/App/Resources/Assets.xcassets/Image/Common/middleSizePet.imageset/my moim@3x.png
  App/App/Resources/Assets.xcassets/Image/Common/petDefaultProfile.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/petDefaultProfile.imageset/profile_dog.png
  App/App/Resources/Assets.xcassets/Image/Common/petDefaultProfile.imageset/profile_dog@2x.png
  App/App/Resources/Assets.xcassets/Image/Common/petDefaultProfile.imageset/profile_dog@3x.png
  App/App/Resources/Assets.xcassets/Image/Common/setting.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/setting.imageset/icon_kebab_menu.png
  App/App/Resources/Assets.xcassets/Image/Common/setting.imageset/icon_kebab_menu@2x.png
  App/App/Resources/Assets.xcassets/Image/Common/setting.imageset/icon_kebab_menu@3x.png
  App/App/Resources/Assets.xcassets/Image/Common/smallSizePet.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/smallSizePet.imageset/Group 234.png
  App/App/Resources/Assets.xcassets/Image/Common/smallSizePet.imageset/Group 234@2x.png
  App/App/Resources/Assets.xcassets/Image/Common/smallSizePet.imageset/Group 234@3x.png
  App/App/Resources/Assets.xcassets/Image/Common/userDefaultProfile.imageset/Contents.json
  App/App/Resources/Assets.xcassets/Image/Common/userDefaultProfile.imageset/profile_user.png
  App/App/Resources/Assets.xcassets/Image/Common/userDefaultProfile.imageset/profile_user@2x.png
  App/App/Resources/Assets.xcassets/Image/Common/userDefaultProfile.imageset/profile_user@3x.png
  App/App/Resources/Assets.xcassets/Image/MyPage/profileSetting.imageset/highlighter.png
  App/App/Resources/Assets.xcassets/Image/MyPage/profileSetting.imageset/highlighter@2x.png
  App/App/Resources/Assets.xcassets/Image/MyPage/profileSetting.imageset/highlighter@3x.png
  App/App/Sources/Common/View/EmptyNoticeView.swift
  App/App/Sources/Extension/UICollectionView+Extension.swift
  App/App/Sources/Extension/UIImage+Extension.swift
  App/App/Sources/Extension/UITableView+Extension.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/View/GatherListCell.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/View/GatherListTableView.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/View/SegmentView.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileReactor.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileViewController.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/DogTableViewCell.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/InitialIntroductionView.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/IntroduceView.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/ProfileContentView.swift
Labels: _요구사항

#83 [feat] 활동 지역 선택
  App/App/Sources/Scenes/AuthScene/Entity/Area.swift
  App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaReactor.swift
Labels: 리뷰끝 머지됨 😘

#84 [feat] 가즈아..
  App/App/Sources/Common/Repository/ProfileRespository.swift
  App/App/Sources/Common/UseCase/KeychainUseCase.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListReactor.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListViewController.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileMainRepositoryInterface.swift
Labels: 리뷰끝 머지됨 😘

#85 [feat] DetailGather API 연동
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Common/Repository/CommentRepository.swift
  App/App/Sources/Common/Repository/DetailGatherRepository.swift
  App/App/Sources/Common/Service/Network/APIConstants.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubDetailInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubFIndDetailResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/CommentInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/LeaderInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/PetSizeTypeDTO.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentRepositoryInterface.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherRepositoryInterface.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListCoordinator.swift
Labels: 리뷰끝 머지됨 😘

#86 [feat] 반려견 추가 부분 수정 / 견종 검색 화면 생성
  App/App.xcodeproj/project.pbxproj
  App/App/Resources/견종목록.csv
  App/App/Sources/Common/View/Tag/TagCollectionView.swift
  App/App/Sources/Common/View/Tag/TagCollectionViewCell.swift
  App/App/Sources/Common/View/Tag/TagCollectionViewReactor.swift
  App/App/Sources/Scenes/BreedSelectScene/SearchBreedReactor.swift
  App/App/Sources/Scenes/BreedSelectScene/SearchBreedViewController.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/View/GatherListTableView.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetContentView.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetReactor.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetViewController.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/Entity/PetRequestDTO.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/Entity/PetTag.swift
  App/App/Sources/Scenes/ProfileScene/ProfileCoordinator.swift
Labels: 리뷰끝 머지됨 😘

#87 [feat] API ID Update
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Common/Service/Network/DTO/Account/PetInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubDetailInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/CommentInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/LeaderInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Common/AccountInfoDTO.swift
  App/App/Sources/Scenes/GatherScene/Entitiy/ClubDetailInfo.swift
  App/App/Sources/Scenes/GatherScene/Entitiy/CommentInfo.swift
  App/App/Sources/Scenes/GatherScene/Entitiy/LeaderInfo.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/Entity/AccountInfo.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/Entity/PetInfo.swift
Labels: 리뷰끝 머지됨 😘

#88 [feat] 반려견 추가, 삭제 API 연동
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Common/Repository/AddPetRepository.swift
  App/App/Sources/Common/Repository/ProfileRespository.swift
  App/App/Sources/Common/Service/Network/APIConstants.swift
  App/App/Sources/Common/View/PaddingLabel.swift
  App/App/Sources/Common/View/Tag/TagCollectionViewCell.swift
  App/App/Sources/Extension/UIImageView+Extension.swift
  App/App/Sources/Scenes/BreedSelectScene/SearchBreedReactor.swift
  App/App/Sources/Scenes/BreedSelectScene/SearchBreedViewController.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetContentView.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetReactor.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetRepositoryInterface.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetViewController.swift
  App/App/Sources/Scenes/ProfileScene/AddPetScene/Entity/PetRequestInfo.swift
  App/App/Sources/Scenes/ProfileScene/EditProfileScene/EditProfileViewController.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/Entity/PetInfo.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileMainRepositoryInterface.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileReactor.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/ProfileViewController.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/IntroduceView.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/PetTableViewCell.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/ProfileContentView.swift
  App/App/Sources/Scenes/ProfileScene/ProfileCoordinator.swift
Labels: 리뷰끝 머지됨 😘

#89 [feat] 상세모임 UI 뚝딱뚝딱..
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Application/SceneDelegate.swift
  App/App/Sources/Common/Repository/GatherListRepository.swift
  App/App/Sources/Common/Service/Network/DTO/Account/AccountSummaryInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubFIndDetailResponseDTO.swift
  App/App/Sources/Common/View/Tag/TagCollectionViewReactor.swift
  App/App/Sources/Extension/UIButton+Extension.swift
  App/App/Sources/Extension/UIImageView+Extension.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/ParticipantCollectionView.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/ParticipantCollectionViewCell.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListCoordinator.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListReactor.swift
  App/App/Sources/Scenes/ProfileScene/MainScene/View/ProfileContentView.swift
Labels: 리뷰끝 머지됨 😘

#95 [feat] mapview, collectionview
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentCell.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/ParticipantCollectionViewCell.swift
Labels: 리뷰끝 머지됨 😘

#97 [feat] 댓글, 태그, 유저 뚝배기
  App/App/Sources/Common/Service/Network/DTO/Club/CommentInfoDTO.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentCell.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/ParticipantCollectionViewCell.swift
  App/App/Sources/Scenes/GatherScene/Entitiy/CommentInfo.swift
Labels: 리뷰끝 머지됨 😘

#98 [feat] 댓글신고
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentCell.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
Labels: 리뷰끝 머지됨 😘

#99 [feat] Date 예쁘게.. 코드 루팡
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentCell.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
Labels: 리뷰끝 머지됨 😘

#100 [feat] 디텡.ㄹ.
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Application/SceneDelegate.swift
  App/App/Sources/Common/Coordinator/TabCoordinator.swift
  App/App/Sources/Common/Repository/DetailGatherRepository.swift
  App/App/Sources/Common/Repository/ProfileRespository.swift
  App/App/Sources/Common/Service/Network/APIConstants.swift
  App/App/Sources/Common/Service/Network/DTO/Account/AccountSummaryInfoDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/ClubFIndDetailResponseDTO.swift
  App/App/Sources/Common/Service/Network/DTO/Club/CommentRequestDTO.swift
  App/App/Sources/Common/Service/Network/Network/NetworkManager.swift
  App/App/Sources/Scenes/AuthScene/AuthCoordinator.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherRepositoryInterface.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
  App/App/Sources/Scenes/GatherScene/Entitiy/CommentInfo.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListCoordinator.swift
Labels: 리뷰끝 머지됨 😘

#101 [feat] api 수정
  App/App.xcodeproj/project.pbxproj
  App/App/Sources/Common/Repository/AccountValidationRepository.swift
  App/App/Sources/Common/Repository/GatherListRepository.swift
  App/App/Sources/Common/Service/Network/APIConstants.swift
  App/App/Sources/Scenes/ChattingScene/ChattingCoordinator.swift
  App/App/Sources/Scenes/ChattingScene/ChattingReactor.swift
  App/App/Sources/Scenes/ChattingScene/ChattingViewController.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
  App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListCoordinator.swift
Labels: 리뷰끝 머지됨 😘

#102 [feat] 모임 생성 api 수정, 조건 수정
  App/App/Sources/Common/Service/Network/DTO/Club/CreateClubRequestDTO.swift
  App/App/Sources/Scenes/CreateGatherScene/CreateGatherReactor.swift
Labels: 리뷰끝 머지됨 😘

#103 [feat] 모임 참여 버튼 시나리오
  App/App/Sources/Common/Repository/DetailGatherRepository.swift
  App/App/Sources/Common/Service/Network/APIConstants.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherRepositoryInterface.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
Labels: 리뷰끝 머지됨 😘

#104 [feat] 댓글신고, 댓글, 모임삭제, 모임나가기,.
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentCell.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
  App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
Labels: 리뷰끝 머지됨 😘
